import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import './tokens.css'
import './style.css'
import './homebase.css'
import './identity.css'
import './motion.css'
import './styles/workspace.css'
import './styles/today.css'
import './styles/rhythm.css'
import './styles/training.css'
import './styles/guide.css'

createApp(App).use(createPinia()).mount('#app')
